services:
  db:
    image: postgres:13
    restart: always
    container_name: coaster-auth-postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: data
    ports:
      - '5432:5432'
  web:
    image: node:20.9.0-alpine3.18
    container_name: coaster-auth-web
    environment:
      - CODESPACES
      - ORIGIN=http://localhost:5173
    ports:
      - '5173:5173'
    env_file:
      - .env.test
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.pnpm-store/
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run migrate && pnpm run dev --host"
    depends_on:
      - db
